spring:
  config:
    activate:
      on-profile: prod

  security:
    user:
      name: yash
      password: awesome

  datasource:
    url: jdbc:mysql://localhost:3306/localPlayer
    username: springuser
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update

music:
  directory:
    path: /home/yash/Music
